# Generated by Django 3.0.1 on 2019-12-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('search', models.CharField(max_length=140, verbose_name='Search')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Historys',
                'db_table': 'history',
            },
        ),
    ]
