# Generated by Django 2.2.6 on 2019-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
