# Generated by Django 2.2.6 on 2019-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20191220_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date'], 'verbose_name': 'History', 'verbose_name_plural': 'Historys'},
        ),
        migrations.AddField(
            model_name='history',
            name='json',
            field=models.TextField(default='', verbose_name='Json'),
            preserve_default=False,
        ),
    ]
